# yamllint disable rule:empty-lines rule:key-ordering rule:brackets
# cspell:word localnet
---
services:
  aptos-node:
    network_mode: 'host'
    image: 'econialabs/aptos-cli:4.1.0'
    profiles: ["test-harness"]
    ports:
    - '50051:50051'
    - '8070:8070'
    - '8090:8090'
    - '8080:8080'
    - '8081:8081'
    healthcheck:
      test: ['CMD', 'curl', 'http://localhost:8070/']
      interval: '5s'
      timeout: '5s'
      retries: 10
      start_period: '60s'
    # In order to start the node with the indexer API; i.e., run
    # `aptos node run-localnet --with-indexer-api`, the Docker socket must
    # be mounted to the container. This mount enables the container to start a
    # new container. Note that this is *not* 'Docker-in-Docker', but rather
    # 'Docker-outside-Docker'. That is, the container can act as the host in
    # terms of creating and orchestrating other containers but still appears as
    # a sibling to the existing containers and any new containers it creates.
    volumes:
    - '/var/run/docker.sock:/var/run/docker.sock'
    entrypoint: [
      'aptos',
      'node',
      'run-localnet',
      '--with-indexer-api',
      '--force-restart',
      '--bind-to',
      '0.0.0.0'
    ]
  test-deployer:
    extra_hosts:
    - 'host.docker.internal:host-gateway'
    build:
      context: ../../
      dockerfile: 'src/docker/test-deployer/Dockerfile'
      args:
        # yamllint disable rule:line-length
        PUBLISHER_PRIVATE_KEY: |-
          ${PUBLISHER_PRIVATE_KEY:-0xf000d910b99722d201c6cf88eb7d1112b43475b9765b118f289b5d65d919000d}
        EMOJICOIN_MODULE_ADDRESS: |-
          ${EMOJICOIN_MODULE_ADDRESS:-0xeaa964d1353b075ac63b0c5a0c1e92aa93355be1402f6077581e37e2a846105e}
        # yamllint enable rule:line-length
    image: 'xbtmatt/emojicoin-dot-fun-test-deployer:latest'
    profiles: ["test-harness"]
    depends_on:
      aptos-node:
        condition: 'service_healthy'
  processor:
    profiles: ["test-harness"]
    depends_on:
      aptos-node:
        condition: 'service_healthy'
...
