---
jobs:
  build-push:
    runs-on: 'ubuntu-latest'
    steps:
    - uses: 'actions/checkout@v4'
    - id: 'metadata'
      uses: 'docker/metadata-action@v5'
      with:
        images: 'xbtmatt/emojicoin-dot-fun-localnet-deployer'
        tags: |
          type=match,pattern=emojicoin-dot-fun-localnet-deployer-v(.*),group=1
    - uses: 'docker/setup-qemu-action@v3'
    - uses: 'docker/setup-buildx-action@v3'
    - uses: 'docker/login-action@v3'
      with:
        password: '${{ secrets.DOCKERHUB_TOKEN }}'
        username: '${{ secrets.DOCKERHUB_USERNAME }}'
    - uses: 'docker/build-push-action@v6'
      with:
        cache-from: 'type=gha'
        cache-to: 'type=gha,mode=max'
        context: '.'
        file: 'src/docker/localnet-deployer/Dockerfile'
        labels: '${{ steps.metadata.outputs.labels }}'
        # The emojicoin-node image can only be built for the platform on which
        # the build is running. This is because the build process requires
        # running `aptos node run-localnet`, which spawns a new container. This
        # new container must be able to run the `aptos` binary, which is only
        # available for the platform on which the build is running.
        platforms: '${{ vars.DOCKER_IMAGE_PLATFORMS }}'
        push: 'true'
        tags: '${{ steps.metadata.outputs.tags }}'
    timeout-minutes: 360
name: 'Build the localnet-deployer Docker image and push to Dockerhub'
'on':
  workflow_dispatch: {}
  push:
    tags:
    - 'emojicoin-dot-fun-localnet-deployer*'
...
